[build]
    functions = "functions"
    publish = "dist"


[[redirects]]
    from = "/api/*"
    to = "https://snapbox-api.herokuapp.com/api/:splat"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200